"use client"
import React from 'react'
import {motion} from "framer-motion";

const cards = {
  initial:{scale:0.95,opacity:0,y:-10},
  hover:{scale:1, transition:{type:"spring",duration:0.8}},
  inview:{opacity:1,y:0,transition:{duration:0.8,delay:0.8,ease:"easeIn",type:"spring"}}
}
export default function ProjectsComponet() {
  return (
    <div className='grid lg:grid-cols-3 md:grid-cols-2 xs:grid-cols-1 gap-2 lg:mt-0 xs:mt-20'>
      <h1 className='text-bold text-primary lg:text-6xl xs:text-4xl lg:col-span-3 md:col-span-2 xs:col-span-1 grid place-content-center m-2'>Projects</h1>
    <motion.div variants={cards} initial="initial" whileHover="hover" whileInView="inview" viewport={{once:false}} className="w-full flex flex-col gap-2 p-2 shadow-lg shadow-secondary min-h-full ">
      <h2 className="text-bold text-primary text-2xl pl-3">Maintenance of SCADA (Maintenace and Commissioning)</h2>
      <div>
        <h4 className="text-bold text-secondary text-xl pl-3">Project Scope</h4>
        <ul>
          <li className="leading-normal max-w-prose p-3 lg:max-w-lg-s md:max-w-md-s">Maintenance and repair of SCADA RTUs and associated field equipment in acrrodance with the requirements of City Power technical pecifications</li>
        </ul>
      </div>
        <footer className="bg-primary pl-3 mt-auto">
          <span className="text-text-primary text-bold">Main Client:</span><span className="text-secondary ml-2">City Power Johannesburg</span><br />
          <span className="text-text-primary text-bold">Our Client:</span><span className="text-secondary ml-2">City Power Secondary Plant</span>
        </footer>
    </motion.div>
    <motion.div variants={cards} initial="initial" whileHover="hover" whileInView="inview" viewport={{once:false}} className="w-full flex flex-col gap-2 p-2 shadow-lg shadow-secondary min-h-full">
      <h2 className="text-bold text-primary text-2xl pl-3">Maintenance of Power Systems (Maintenace and Commissioning)</h2>
      <div>
        <h4 className="text-bold text-secondary text-xl pl-3">Project Scope</h4>
        <ul>
          <li className="leading-normal max-w-prose p-3 lg:max-w-lg-s md:max-w-md-s">Installation</li>
          <li className="leading-normal max-w-prose p-3 lg:max-w-lg-s md:max-w-md-s">Commissioning</li>
          <li className="leading-normal max-w-prose p-3 lg:max-w-lg-s md:max-w-md-s">Testing and Maintenance of the protection and control schemes on the transmission and distribution network in accordance with the requirements of City Power Technical Specification</li>
        </ul>
      </div>
        <footer className="bg-primary pl-3 mt-auto">
          <span className="text-text-primary text-bold">Main Client:</span><span className="text-secondary ml-2">City Power Johannesburg(SOC)Ltd</span><br />
          <span className="text-text-primary text-bold">Our Client:</span><span className="text-secondary ml-2">City Power Secondary Plant</span>
        </footer>
    </motion.div>
    <motion.div variants={cards} initial="initial" whileHover="hover" whileInView="inview" viewport={{once:false}} className="w-full flex flex-col gap-2 p-2 shadow-lg shadow-secondary min-h-full">
      <h2 className="text-bold text-primary text-2xl pl-3">132/33kV Karusa and Soetwater Substation (Commissioning)</h2>
      <div>
        <h4 className="text-bold text-secondary text-xl pl-3">Project Scope</h4>
        <ul>
          <li className="leading-normal max-w-prose p-3 lg:max-w-lg-s md:max-w-md-s">To commission substation and automation system for the Kuresa and Soetwater Windfarm substations project in accordince with the requirements of Enel Green Power South Africa technical specification of the Functional Design Specification(FDS) as generated by Cnco and approved by Enel Power South Africa.</li>
        </ul>
      </div>
        <footer className="bg-primary pl-3 mt-auto">
          <span className="text-text-primary text-bold">Main Client:</span><span className="text-secondary ml-2">Enel Green Power South Africa and Eskom</span><br />
          <span className="text-text-primary text-bold">Our Client:</span><span className="text-secondary ml-2">Conco Energy Solutions</span>
        </footer>
    </motion.div>
    <motion.div variants={cards} initial="initial" whileHover="hover" whileInView="inview" viewport={{once:false}} className="w-full flex flex-col gap-2 p-2 shadow-lg shadow-secondary min-h-full">
      <h2 className="text-bold text-primary text-2xl pl-3">66/11/3.3kV Mindola Sunstation upgrade (Commissioning)</h2>
      <div>
        <h4 className="text-bold text-secondary text-xl pl-3">Project Scope</h4>
        <ul>
          <li className="leading-normal max-w-prose p-3 lg:max-w-lg-s md:max-w-md-s">To commission substation abd automation system for the Mindola sub-station upgrade project in acccordance with the requirements of CEC technical specification and the funtiontal design specification (FDS) as generated by Conco and approved by CEC.</li>
        </ul>
      </div>
        <footer className="bg-primary pl-3 mt-auto">
          <span className="text-text-primary text-bold">Main Client:</span><span className="text-secondary ml-2">CEC</span><br />
          <span className="text-text-primary text-bold">Our Client:</span><span className="text-secondary ml-2">Conco Energy Solutions</span>
        </footer>
    </motion.div>
    <motion.div variants={cards} initial="initial" whileHover="hover" whileInView="inview" viewport={{once:false}} className="w-full flex flex-col gap-2 p-2 shadow-lg shadow-secondary min-h-full">
      <h2 className="text-bold text-primary text-2xl pl-3">132/33kV Kromrivier Substation (Commissioning)</h2>
      <div>
        <h4 className="text-bold text-secondary text-xl pl-3">Project Scope</h4>
        <ul>
          <li className="leading-normal max-w-prose p-3 lg:max-w-lg-s md:max-w-md-s">To commission substation abd automation system for the Oyster Bay windfarm sub-station project in acccordance with the requirements of Enel Green Power South Africa technical specification and the funtiontal design specification (FDS) as generated by Conco and approved by Enel Green Power South Africa. </li>
        </ul>
      </div>
        <footer className="bg-primary pl-3 mt-auto">
          <span className="text-text-primary text-bold">Main Client:</span><span className="text-secondary ml-2">Enel Green Power South Africa and Eskom</span><br />
          <span className="text-text-primary text-bold">Our Client:</span><span className="text-secondary ml-2">Conco Energy Solutions</span>
        </footer>
    </motion.div>
    <motion.div variants={cards} initial="initial" whileHover="hover" whileInView="inview" viewport={{once:false}} className="w-full flex flex-col gap-2 p-2 shadow-lg shadow-secondary min-h-full">
      <h2 className="text-bold text-primary text-2xl pl-3">ABB (EPMV AND EPDS)</h2>
      <div>
        <h4 className="text-bold text-secondary text-xl pl-3">Project Scope</h4>
        <ul>
          <li className="leading-normal max-w-prose p-3 lg:max-w-lg-s md:max-w-md-s">To do wiring of switchgear/protection panels.</li>
          <li className="leading-normal max-w-prose p-3 lg:max-w-lg-s md:max-w-md-s">To Carryout internal/routing testing.</li>
          <li className="leading-normal max-w-prose p-3 lg:max-w-lg-s md:max-w-md-s">Factpry Acceptance Testing (FAT).</li>
          <li className="leading-normal max-w-prose p-3 lg:max-w-lg-s md:max-w-md-s">Installation and Commissioning (SAT) of ABB Switchgear / Protection panels.</li>
        </ul>
      </div>
        <footer className="bg-primary pl-3 mt-auto">
          <span className="text-text-primary text-bold">Main Client:</span><span className="text-secondary ml-2">ABB Clients (SASOL,AMAZON,ANGLO AMERICAN AND MUNICIPALITITES)</span><br />
          <span className="text-text-primary text-bold">Our Client:</span><span className="text-secondary ml-2">ABB</span>
        </footer>
    </motion.div>
    <motion.div variants={cards} initial="initial" whileHover="hover" whileInView="inview" viewport={{once:false}} className="w-full flex flex-col gap-2 p-2 shadow-lg shadow-secondary min-h-full">
      <h2 className="text-bold text-primary text-2xl pl-3">132kV Rietvlei in-feed Substation upgrade (Commissioning)</h2>
      <div>
        <h4 className="text-bold text-secondary text-xl pl-3">Project Scope</h4>
        <ul>
          <li className="leading-normal max-w-prose p-3 lg:max-w-lg-s md:max-w-md-s">To design, manufacture, supply, Install and commissioning substation automation system for the Reitvlei 132kV infeed station upgrade project in accordance with requirements of City Of Tshwane technical specification and Functional Design Specification (FDS) as generated by Siemens LTD and approved by City Of Tshwane.<br />
          The project scope also included comprehensive training for City Of Tshwane personnel on all substation automation system delivered uder this project.
          </li>
        </ul>
      </div>
        <footer className="bg-primary pl-3 mt-auto">
          <span className="text-text-primary text-bold">Main Client:</span><span className="text-secondary ml-2">City Of Tshwane</span><br />
          <span className="text-text-primary text-bold">Our Client:</span><span className="text-secondary ml-2">Siemens/Oxygen Projects</span>
        </footer>
    </motion.div>
    <motion.div variants={cards} initial="initial" whileHover="hover" whileInView="inview" viewport={{once:false}} className="w-full flex flex-col gap-2 p-2 shadow-lg shadow-secondary min-h-full">
      <h2 className="text-bold text-primary text-2xl pl-3">132kV Soutpan infeed Substation upgrade (Commissioning)</h2>
      <div>
        <h4 className="text-bold text-secondary text-xl pl-3 mt-auto">Project Scope</h4>
        <ul>
          <li className="leading-normal max-w-prose p-3 lg:max-w-lg-s md:max-w-md-s">To design, manufacture, supply, Install and commissioning substation automation system for the Soutpan 132kV infeed station upgrade project in accordance with requirements of Eskom technical specification and Functional Design Specification (FDS) as generated by ABB South Africa and approved by Eskom.</li>
        </ul>
      </div>
        <footer className="bg-primary pl-3 mt-auto">
          <span className="text-text-primary text-bold">Main Client:</span><span className="text-secondary ml-2">Eskom</span><br />
          <span className="text-text-primary text-bold">Our Client:</span><span className="text-secondary ml-2">ABB/ Nzimata Enterprise</span>
        </footer>
    </motion.div>
    
    </div>
  )
}
